[package]
name = "wordle_finder"
version = "1.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.14"
regex = "1.5.4"
web-view = "0.7.3"
